// https://www.masswerk.at/6502/6502_instruction_set.html#layout

use super::{address::AddressMode as AdrMode, register::CpuRegister as Reg};
use lazy_static::lazy_static;
use std::collections::HashMap;

#[derive(Debug)]
pub struct Opcode {
    pub asm: Asm,
    pub adr_mode: AdrMode,
    pub cycle: u8,
}

impl Opcode {
    fn new(asm: Asm, adr_mode: AdrMode, cycle: u8) -> Self {
        Self {
            asm,
            adr_mode,
            cycle,
        }
    }

    pub fn len(&self) -> u8 {
        match self.adr_mode {
            AdrMode::Implied(_) => 1,
            AdrMode::Absolute | AdrMode::AbsoluteX | AdrMode::AbsoluteY | AdrMode::Indirect => 3,
            _ => 2,
        }
    }

    pub fn get_additional_cycles(&self, crossed_boundary: bool) -> u8 {
        match self.adr_mode {
            AdrMode::AbsoluteX | AdrMode::AbsoluteY | AdrMode::IndirectY
                if self.asm != Asm::STA =>
            {
                (crossed_boundary && self.cycle < 6) as u8
            }
            _ => 0,
        }
    }

    pub fn is_branching(&self) -> bool {
        matches!(
            self.asm,
            Asm::BCC | Asm::BCS | Asm::BVC | Asm::BVS | Asm::BEQ | Asm::BMI | Asm::BNE | Asm::BPL
        )
    }
}

#[derive(Debug, PartialEq)]
#[allow(clippy::upper_case_acronyms)]
pub enum Asm {
    LDA,
    LDX,
    LDY,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    PHA,
    PHP,
    PLA,
    PLP,
    DEC,
    DEX,
    DEY,
    INC,
    INX,
    INY,
    ADC,
    SBC,
    AND,
    EOR,
    ORA,
    ASL,
    LSR,
    ROL,
    ROR,
    CLC,
    CLD,
    CLI,
    CLV,
    SEC,
    SED,
    SEI,
    CMP,
    CPX,
    CPY,
    BCC,
    BCS,
    BVC,
    BVS,
    BEQ,
    BMI,
    BNE,
    BPL,
    JMP,
    JSR,
    RTS,
    BRK,
    RTI,
    BIT,
    NOP,
    ALR,
    ANC,
    LAS,
    LAX,
    SAX,
    SBX,
    DCP,
    ISB,
    SLO,
    RLA,
    SRE,
    RRA,
}

lazy_static! {
    pub static ref OPCODE_MAP: HashMap<u8, Opcode> = HashMap::from([
        (0xA9, Opcode::new(Asm::LDA, AdrMode::Immediate, 2)),
        (0xA5, Opcode::new(Asm::LDA, AdrMode::ZeroPage, 3)),
        (0xB5, Opcode::new(Asm::LDA, AdrMode::ZeroPageX, 4)),
        (0xAD, Opcode::new(Asm::LDA, AdrMode::Absolute, 4)),
        (0xBD, Opcode::new(Asm::LDA, AdrMode::AbsoluteX, 4)),
        (0xB9, Opcode::new(Asm::LDA, AdrMode::AbsoluteY, 4)),
        (0xA1, Opcode::new(Asm::LDA, AdrMode::IndirectX, 6)),
        (0xB1, Opcode::new(Asm::LDA, AdrMode::IndirectY, 5)),
        (0xA2, Opcode::new(Asm::LDX, AdrMode::Immediate, 2)),
        (0xA6, Opcode::new(Asm::LDX, AdrMode::ZeroPage, 3)),
        (0xB6, Opcode::new(Asm::LDX, AdrMode::ZeroPageY, 4)),
        (0xAE, Opcode::new(Asm::LDX, AdrMode::Absolute, 4)),
        (0xBE, Opcode::new(Asm::LDX, AdrMode::AbsoluteY, 4)),
        (0xA0, Opcode::new(Asm::LDY, AdrMode::Immediate, 2)),
        (0xA4, Opcode::new(Asm::LDY, AdrMode::ZeroPage, 3)),
        (0xB4, Opcode::new(Asm::LDY, AdrMode::ZeroPageX, 4)),
        (0xAC, Opcode::new(Asm::LDY, AdrMode::Absolute, 4)),
        (0xBC, Opcode::new(Asm::LDY, AdrMode::AbsoluteX, 4)),
        (0x85, Opcode::new(Asm::STA, AdrMode::ZeroPage, 3)),
        (0x95, Opcode::new(Asm::STA, AdrMode::ZeroPageX, 4)),
        (0x8D, Opcode::new(Asm::STA, AdrMode::Absolute, 4)),
        (0x9D, Opcode::new(Asm::STA, AdrMode::AbsoluteX, 5)),
        (0x99, Opcode::new(Asm::STA, AdrMode::AbsoluteY, 5)),
        (0x81, Opcode::new(Asm::STA, AdrMode::IndirectX, 6)),
        (0x91, Opcode::new(Asm::STA, AdrMode::IndirectY, 6)),
        (0x86, Opcode::new(Asm::STX, AdrMode::ZeroPage, 3)),
        (0x96, Opcode::new(Asm::STX, AdrMode::ZeroPageY, 4)),
        (0x8E, Opcode::new(Asm::STX, AdrMode::Absolute, 4)),
        (0x84, Opcode::new(Asm::STY, AdrMode::ZeroPage, 3)),
        (0x94, Opcode::new(Asm::STY, AdrMode::ZeroPageX, 4)),
        (0x8C, Opcode::new(Asm::STY, AdrMode::Absolute, 4)),
        (0xAA, Opcode::new(Asm::TAX, AdrMode::Implied(Reg::X), 2)),
        (0xA8, Opcode::new(Asm::TAY, AdrMode::Implied(Reg::Y), 2)),
        (0xBA, Opcode::new(Asm::TSX, AdrMode::Implied(Reg::X), 2)),
        (0x8A, Opcode::new(Asm::TXA, AdrMode::Implied(Reg::AC), 2)),
        (0x9A, Opcode::new(Asm::TXS, AdrMode::Implied(Reg::SP), 2)),
        (0x98, Opcode::new(Asm::TYA, AdrMode::Implied(Reg::AC), 2)),
        (0xC6, Opcode::new(Asm::DEC, AdrMode::ZeroPage, 5)),
        (0xD6, Opcode::new(Asm::DEC, AdrMode::ZeroPageX, 6)),
        (0xCE, Opcode::new(Asm::DEC, AdrMode::Absolute, 6)),
        (0xDE, Opcode::new(Asm::DEC, AdrMode::AbsoluteX, 7)),
        (0xCA, Opcode::new(Asm::DEX, AdrMode::Implied(Reg::X), 2)),
        (0x88, Opcode::new(Asm::DEY, AdrMode::Implied(Reg::Y), 2)),
        (0xE6, Opcode::new(Asm::INC, AdrMode::ZeroPage, 5)),
        (0xF6, Opcode::new(Asm::INC, AdrMode::ZeroPageX, 6)),
        (0xEE, Opcode::new(Asm::INC, AdrMode::Absolute, 6)),
        (0xFE, Opcode::new(Asm::INC, AdrMode::AbsoluteX, 7)),
        (0xE8, Opcode::new(Asm::INX, AdrMode::Implied(Reg::X), 2)),
        (0xC8, Opcode::new(Asm::INY, AdrMode::Implied(Reg::Y), 2)),
        (0x48, Opcode::new(Asm::PHA, AdrMode::Implied(Reg::AC), 3)),
        (0x08, Opcode::new(Asm::PHP, AdrMode::Implied(Reg::SR), 3)),
        (0x68, Opcode::new(Asm::PLA, AdrMode::Implied(Reg::AC), 4)),
        (0x28, Opcode::new(Asm::PLP, AdrMode::Implied(Reg::SR), 4)),
        (0x69, Opcode::new(Asm::ADC, AdrMode::Immediate, 2)),
        (0x65, Opcode::new(Asm::ADC, AdrMode::ZeroPage, 3)),
        (0x75, Opcode::new(Asm::ADC, AdrMode::ZeroPageX, 4)),
        (0x6D, Opcode::new(Asm::ADC, AdrMode::Absolute, 4)),
        (0x7D, Opcode::new(Asm::ADC, AdrMode::AbsoluteX, 4)),
        (0x79, Opcode::new(Asm::ADC, AdrMode::AbsoluteY, 4)),
        (0x61, Opcode::new(Asm::ADC, AdrMode::IndirectX, 6)),
        (0x71, Opcode::new(Asm::ADC, AdrMode::IndirectY, 5)),
        (0xE9, Opcode::new(Asm::SBC, AdrMode::Immediate, 2)),
        (0xE5, Opcode::new(Asm::SBC, AdrMode::ZeroPage, 3)),
        (0xF5, Opcode::new(Asm::SBC, AdrMode::ZeroPageX, 4)),
        (0xED, Opcode::new(Asm::SBC, AdrMode::Absolute, 4)),
        (0xFD, Opcode::new(Asm::SBC, AdrMode::AbsoluteX, 4)),
        (0xF9, Opcode::new(Asm::SBC, AdrMode::AbsoluteY, 4)),
        (0xE1, Opcode::new(Asm::SBC, AdrMode::IndirectX, 6)),
        (0xF1, Opcode::new(Asm::SBC, AdrMode::IndirectY, 5)),
        (0x29, Opcode::new(Asm::AND, AdrMode::Immediate, 2)),
        (0x25, Opcode::new(Asm::AND, AdrMode::ZeroPage, 3)),
        (0x35, Opcode::new(Asm::AND, AdrMode::ZeroPageX, 4)),
        (0x2D, Opcode::new(Asm::AND, AdrMode::Absolute, 4)),
        (0x3D, Opcode::new(Asm::AND, AdrMode::AbsoluteX, 4)),
        (0x39, Opcode::new(Asm::AND, AdrMode::AbsoluteY, 4)),
        (0x21, Opcode::new(Asm::AND, AdrMode::IndirectX, 6)),
        (0x31, Opcode::new(Asm::AND, AdrMode::IndirectY, 5)),
        (0x49, Opcode::new(Asm::EOR, AdrMode::Immediate, 2)),
        (0x45, Opcode::new(Asm::EOR, AdrMode::ZeroPage, 3)),
        (0x55, Opcode::new(Asm::EOR, AdrMode::ZeroPageX, 4)),
        (0x4D, Opcode::new(Asm::EOR, AdrMode::Absolute, 4)),
        (0x5D, Opcode::new(Asm::EOR, AdrMode::AbsoluteX, 4)),
        (0x59, Opcode::new(Asm::EOR, AdrMode::AbsoluteY, 4)),
        (0x41, Opcode::new(Asm::EOR, AdrMode::IndirectX, 6)),
        (0x51, Opcode::new(Asm::EOR, AdrMode::IndirectY, 5)),
        (0x09, Opcode::new(Asm::ORA, AdrMode::Immediate, 2)),
        (0x05, Opcode::new(Asm::ORA, AdrMode::ZeroPage, 3)),
        (0x15, Opcode::new(Asm::ORA, AdrMode::ZeroPageX, 4)),
        (0x0D, Opcode::new(Asm::ORA, AdrMode::Absolute, 4)),
        (0x1D, Opcode::new(Asm::ORA, AdrMode::AbsoluteX, 4)),
        (0x19, Opcode::new(Asm::ORA, AdrMode::AbsoluteY, 4)),
        (0x01, Opcode::new(Asm::ORA, AdrMode::IndirectX, 6)),
        (0x11, Opcode::new(Asm::ORA, AdrMode::IndirectY, 5)),
        (0x0A, Opcode::new(Asm::ASL, AdrMode::Implied(Reg::AC), 2)),
        (0x06, Opcode::new(Asm::ASL, AdrMode::ZeroPage, 5)),
        (0x16, Opcode::new(Asm::ASL, AdrMode::ZeroPageX, 6)),
        (0x0E, Opcode::new(Asm::ASL, AdrMode::Absolute, 6)),
        (0x1E, Opcode::new(Asm::ASL, AdrMode::AbsoluteX, 7)),
        (0x4A, Opcode::new(Asm::LSR, AdrMode::Implied(Reg::AC), 2)),
        (0x46, Opcode::new(Asm::LSR, AdrMode::ZeroPage, 5)),
        (0x56, Opcode::new(Asm::LSR, AdrMode::ZeroPageX, 6)),
        (0x4E, Opcode::new(Asm::LSR, AdrMode::Absolute, 6)),
        (0x5E, Opcode::new(Asm::LSR, AdrMode::AbsoluteX, 7)),
        (0x2A, Opcode::new(Asm::ROL, AdrMode::Implied(Reg::AC), 2)),
        (0x26, Opcode::new(Asm::ROL, AdrMode::ZeroPage, 5)),
        (0x36, Opcode::new(Asm::ROL, AdrMode::ZeroPageX, 6)),
        (0x2E, Opcode::new(Asm::ROL, AdrMode::Absolute, 6)),
        (0x3E, Opcode::new(Asm::ROL, AdrMode::AbsoluteX, 7)),
        (0x6A, Opcode::new(Asm::ROR, AdrMode::Implied(Reg::AC), 2)),
        (0x66, Opcode::new(Asm::ROR, AdrMode::ZeroPage, 5)),
        (0x76, Opcode::new(Asm::ROR, AdrMode::ZeroPageX, 6)),
        (0x6E, Opcode::new(Asm::ROR, AdrMode::Absolute, 6)),
        (0x7E, Opcode::new(Asm::ROR, AdrMode::AbsoluteX, 7)),
        (0x18, Opcode::new(Asm::CLC, AdrMode::Implied(Reg::SR), 2)),
        (0xD8, Opcode::new(Asm::CLD, AdrMode::Implied(Reg::SR), 2)),
        (0x58, Opcode::new(Asm::CLI, AdrMode::Implied(Reg::SR), 2)),
        (0xB8, Opcode::new(Asm::CLV, AdrMode::Implied(Reg::SR), 2)),
        (0x38, Opcode::new(Asm::SEC, AdrMode::Implied(Reg::SR), 2)),
        (0xF8, Opcode::new(Asm::SED, AdrMode::Implied(Reg::SR), 2)),
        (0x78, Opcode::new(Asm::SEI, AdrMode::Implied(Reg::SR), 2)),
        (0xC9, Opcode::new(Asm::CMP, AdrMode::Immediate, 2)),
        (0xC5, Opcode::new(Asm::CMP, AdrMode::ZeroPage, 3)),
        (0xD5, Opcode::new(Asm::CMP, AdrMode::ZeroPageX, 4)),
        (0xCD, Opcode::new(Asm::CMP, AdrMode::Absolute, 4)),
        (0xDD, Opcode::new(Asm::CMP, AdrMode::AbsoluteX, 4)),
        (0xD9, Opcode::new(Asm::CMP, AdrMode::AbsoluteY, 4)),
        (0xC1, Opcode::new(Asm::CMP, AdrMode::IndirectX, 6)),
        (0xD1, Opcode::new(Asm::CMP, AdrMode::IndirectY, 5)),
        (0xE0, Opcode::new(Asm::CPX, AdrMode::Immediate, 2)),
        (0xE4, Opcode::new(Asm::CPX, AdrMode::ZeroPage, 3)),
        (0xEC, Opcode::new(Asm::CPX, AdrMode::Absolute, 4)),
        (0xC0, Opcode::new(Asm::CPY, AdrMode::Immediate, 2)),
        (0xC4, Opcode::new(Asm::CPY, AdrMode::ZeroPage, 3)),
        (0xCC, Opcode::new(Asm::CPY, AdrMode::Absolute, 4)),
        (0x90, Opcode::new(Asm::BCC, AdrMode::Relative, 2)),
        (0xB0, Opcode::new(Asm::BCS, AdrMode::Relative, 2)),
        (0xF0, Opcode::new(Asm::BEQ, AdrMode::Relative, 2)),
        (0x30, Opcode::new(Asm::BMI, AdrMode::Relative, 2)),
        (0xD0, Opcode::new(Asm::BNE, AdrMode::Relative, 2)),
        (0x10, Opcode::new(Asm::BPL, AdrMode::Relative, 2)),
        (0x50, Opcode::new(Asm::BVC, AdrMode::Relative, 2)),
        (0x70, Opcode::new(Asm::BVS, AdrMode::Relative, 2)),
        (0x4C, Opcode::new(Asm::JMP, AdrMode::Absolute, 3)),
        (0x6C, Opcode::new(Asm::JMP, AdrMode::Indirect, 5)),
        (0x20, Opcode::new(Asm::JSR, AdrMode::Absolute, 6)),
        (0x60, Opcode::new(Asm::RTS, AdrMode::Implied(Reg::PC), 6)),
        (0x00, Opcode::new(Asm::BRK, AdrMode::Implied(Reg::PC), 7)),
        (0x40, Opcode::new(Asm::RTI, AdrMode::Implied(Reg::PC), 6)),
        (0x24, Opcode::new(Asm::BIT, AdrMode::ZeroPage, 3)),
        (0x2C, Opcode::new(Asm::BIT, AdrMode::Absolute, 4)),
        (0xEA, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0x1A, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0x3A, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0x5A, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0x7A, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0xDA, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0xFA, Opcode::new(Asm::NOP, AdrMode::Implied(Reg::PC), 2)),
        (0x80, Opcode::new(Asm::NOP, AdrMode::Immediate, 2)),
        (0x82, Opcode::new(Asm::NOP, AdrMode::Immediate, 2)),
        (0x89, Opcode::new(Asm::NOP, AdrMode::Immediate, 2)),
        (0xC2, Opcode::new(Asm::NOP, AdrMode::Immediate, 2)),
        (0xE2, Opcode::new(Asm::NOP, AdrMode::Immediate, 2)),
        (0x04, Opcode::new(Asm::NOP, AdrMode::ZeroPage, 3)),
        (0x44, Opcode::new(Asm::NOP, AdrMode::ZeroPage, 3)),
        (0x64, Opcode::new(Asm::NOP, AdrMode::ZeroPage, 3)),
        (0x14, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0x34, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0x54, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0x74, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0xD4, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0xF4, Opcode::new(Asm::NOP, AdrMode::ZeroPageX, 4)),
        (0x0C, Opcode::new(Asm::NOP, AdrMode::Absolute, 4)),
        (0x1C, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0x3C, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0x5C, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0x7C, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0xDC, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0xFC, Opcode::new(Asm::NOP, AdrMode::AbsoluteX, 4)),
        (0x4B, Opcode::new(Asm::ALR, AdrMode::Immediate, 2)),
        (0x0B, Opcode::new(Asm::ANC, AdrMode::Immediate, 2)),
        (0x2B, Opcode::new(Asm::ANC, AdrMode::Immediate, 2)),
        (0xC7, Opcode::new(Asm::DCP, AdrMode::ZeroPage, 5)),
        (0xD7, Opcode::new(Asm::DCP, AdrMode::ZeroPageX, 6)),
        (0xCF, Opcode::new(Asm::DCP, AdrMode::Absolute, 6)),
        (0xDF, Opcode::new(Asm::DCP, AdrMode::AbsoluteX, 7)),
        (0xDB, Opcode::new(Asm::DCP, AdrMode::AbsoluteY, 7)),
        (0xC3, Opcode::new(Asm::DCP, AdrMode::IndirectX, 8)),
        (0xD3, Opcode::new(Asm::DCP, AdrMode::IndirectY, 8)),
        (0xE7, Opcode::new(Asm::ISB, AdrMode::ZeroPage, 5)),
        (0xF7, Opcode::new(Asm::ISB, AdrMode::ZeroPageX, 6)),
        (0xEF, Opcode::new(Asm::ISB, AdrMode::Absolute, 6)),
        (0xFF, Opcode::new(Asm::ISB, AdrMode::AbsoluteX, 7)),
        (0xFB, Opcode::new(Asm::ISB, AdrMode::AbsoluteY, 7)),
        (0xE3, Opcode::new(Asm::ISB, AdrMode::IndirectX, 8)),
        (0xF3, Opcode::new(Asm::ISB, AdrMode::IndirectY, 8)),
        (0xBB, Opcode::new(Asm::LAS, AdrMode::AbsoluteY, 4)),
        (0xA7, Opcode::new(Asm::LAX, AdrMode::ZeroPage, 3)),
        (0xB7, Opcode::new(Asm::LAX, AdrMode::ZeroPageY, 4)),
        (0xAF, Opcode::new(Asm::LAX, AdrMode::Absolute, 4)),
        (0xBF, Opcode::new(Asm::LAX, AdrMode::AbsoluteY, 4)),
        (0xA3, Opcode::new(Asm::LAX, AdrMode::IndirectX, 6)),
        (0xB3, Opcode::new(Asm::LAX, AdrMode::IndirectY, 5)),
        (0x27, Opcode::new(Asm::RLA, AdrMode::ZeroPage, 5)),
        (0x37, Opcode::new(Asm::RLA, AdrMode::ZeroPageX, 6)),
        (0x2F, Opcode::new(Asm::RLA, AdrMode::Absolute, 6)),
        (0x3F, Opcode::new(Asm::RLA, AdrMode::AbsoluteX, 7)),
        (0x3B, Opcode::new(Asm::RLA, AdrMode::AbsoluteY, 7)),
        (0x23, Opcode::new(Asm::RLA, AdrMode::IndirectX, 8)),
        (0x33, Opcode::new(Asm::RLA, AdrMode::IndirectY, 8)),
        (0x67, Opcode::new(Asm::RRA, AdrMode::ZeroPage, 5)),
        (0x77, Opcode::new(Asm::RRA, AdrMode::ZeroPageX, 6)),
        (0x6F, Opcode::new(Asm::RRA, AdrMode::Absolute, 6)),
        (0x7F, Opcode::new(Asm::RRA, AdrMode::AbsoluteX, 7)),
        (0x7B, Opcode::new(Asm::RRA, AdrMode::AbsoluteY, 7)),
        (0x63, Opcode::new(Asm::RRA, AdrMode::IndirectX, 8)),
        (0x73, Opcode::new(Asm::RRA, AdrMode::IndirectY, 8)),
        (0x87, Opcode::new(Asm::SAX, AdrMode::ZeroPage, 3)),
        (0x97, Opcode::new(Asm::SAX, AdrMode::ZeroPageY, 4)),
        (0x8F, Opcode::new(Asm::SAX, AdrMode::Absolute, 4)),
        (0x83, Opcode::new(Asm::SAX, AdrMode::IndirectX, 6)),
        (0xCB, Opcode::new(Asm::SBX, AdrMode::Immediate, 2)),
        (0xEB, Opcode::new(Asm::SBC, AdrMode::Immediate, 2)),
        (0x07, Opcode::new(Asm::SLO, AdrMode::ZeroPage, 5)),
        (0x17, Opcode::new(Asm::SLO, AdrMode::ZeroPageX, 6)),
        (0x0F, Opcode::new(Asm::SLO, AdrMode::Absolute, 6)),
        (0x1F, Opcode::new(Asm::SLO, AdrMode::AbsoluteX, 7)),
        (0x1B, Opcode::new(Asm::SLO, AdrMode::AbsoluteY, 7)),
        (0x03, Opcode::new(Asm::SLO, AdrMode::IndirectX, 8)),
        (0x13, Opcode::new(Asm::SLO, AdrMode::IndirectY, 8)),
        (0x47, Opcode::new(Asm::SRE, AdrMode::ZeroPage, 5)),
        (0x57, Opcode::new(Asm::SRE, AdrMode::ZeroPageX, 6)),
        (0x4F, Opcode::new(Asm::SRE, AdrMode::Absolute, 6)),
        (0x5F, Opcode::new(Asm::SRE, AdrMode::AbsoluteX, 7)),
        (0x5B, Opcode::new(Asm::SRE, AdrMode::AbsoluteY, 7)),
        (0x43, Opcode::new(Asm::SRE, AdrMode::IndirectX, 8)),
        (0x53, Opcode::new(Asm::SRE, AdrMode::IndirectY, 8)),
    ]);
}
