name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --workspace --lib --verbose

      - name: Lint
        run: cargo clippy -- -D warnings
